{{- if .Values.enableDevopsRbacs -}}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: devops-role
rules:
  - apiGroups: [ "*" ]
    resources: [ "*" ]
    verbs: [ "*" ]
  - nonResourceURLs: [ "*" ]
    verbs: [ "*" ]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: devops-role-binding
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: devops-role
subjects:
  - kind: Group
    name: devops
    apiGroup: rbac.authorization.k8s.io
{{- end }}