name: Lint and Test Charts

on:
  pull_request:
    paths:
      - 'stable/**'

jobs:
  lint-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run chart-testing (lint)
        uses: helm/chart-testing-action@v2.6.1
        with:
          command: lint
          config: .github/ct.yaml

  install-chart:
    name: Install and Test Chart
    runs-on: ubuntu-latest
    needs: lint-chart
    strategy:
      matrix:
        k8s:
          - v1.33.0
          - v1.32.0
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create kind ${{ matrix.k8s }} cluster
        uses: helm/kind-action@v1.10.0
        with:
          node_image: kindest/node:${{ matrix.k8s }}

      - name: Run chart-testing (install)
        uses: helm/chart-testing-action@v2.6.1
        with:
          command: install
          config: .github/ct.yaml
